language: node_js
node_js:
    - "15"
    - "14"
    - "6"
    - "5"
    - "4"
    - "0.12.17"
    - "iojs"
script:
    - npm run coverage
after_script:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
